### ISSUE TITLE
README: Paypal link is a `mailto:` email address instead of paypal link

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FPA#12]
https://github.com/FreeCAD/FPA#donations

**Comment by luzpaz** [comment]
Also is this paypal legit? https://twitter.com/iplovodiug/status/1540629526153232385

**Comment by yorikvanhavre** [comment]
Fixed with https://github.com/FreeCAD/FPA/commit/72d0567a04ff69065f616863cfc5b018fb8610b3
