### ISSUE TITLE
Extension to Component Library

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#121]
2 payments of 500 USD as approved here: https://forum.freecad.org/viewtopic.php?t=82156

Payable via PayPal to amulya1171@gmail.com

**Comment by WandererFan** [comment]
Installment 1 500 USD paid via PayPal 2024-01-09.

**Comment by chennes** [comment]
The final report for the project can be found here:
https://github.com/FreeCAD/FPA/blob/main/reports/2024_01_15_Paritosh_Dynamic%20Attributes%20report.pdf

**Comment by WandererFan** [comment]
Installment 2 500 USD paid via PayPal 2024-01-16.
