### ISSUE TITLE
Roll-up banner for FOSDEM + FreeCAD day

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FPA#122]
Total paid: 38.78 EUR
[opencollective issue](https://opencollective.com/freecad/expenses/182078)

**Comment by WandererFan** [comment]
Did you mean to reopen this?  It looks like it has been paid out on OC.

**Comment by yorikvanhavre** [comment]
No we can close it. I thought I wasn't sure you had it encoded and didn't want it to fall out of the radar
