### ISSUE TITLE
Incidental Infrastructure Costs

### ISSUE THREAD

**Issue by kkremitzki** [FreeCAD/FPA#128]
Since the project mentioned in #112 is running longer than expected, I have not yet requested additional funding from DigitalOcean to cover our unoptimized infrastructure costs, and the $800/yr sponsorship from last May has already been exhausted.

I will soon request additional funding with the added justification/marketing content provided by the blog post documentation part of phase 2 for #112, which will likely be approved, but the January 2024 bill of $142.71 has come due already.

Additionally, we use a separate domain for the infrastructure itself, freecad.io, which needs renewal within the next month. Unfortunately, this domain has had a price increase, so the renewal cost for that through Gandi is now $69.99. I would like to renew this domain, but only for another year, enough to provide time for a migration, either to a cheaper separate domain, or to combine those resources onto freecad.org. (Part of the reason for the use of a separation domain is for historical reasons that no longer apply.)

So, this issue is to request $212.70 to cover these two (hopefully incidental) costs.

**Comment by WandererFan** [comment]
IIUC...

January 2024 Infrastructure expense $142.71 - reimburse Kurt for payment to ???vendor???
freecad.io domain renewal 1 year $69.99 - reimburse Kurt for payment to Gandi

**Comment by WandererFan** [comment]
Paid via PayPal 2024-02-10.

**Comment by kkremitzki** [comment]
> IIUC...
> 
> January 2024 Infrastructure expense $142.71 - reimburse Kurt for payment to ???vendor???

First vendor, for the record, is DigitalOcean.

**Comment by WandererFan** [comment]
TY.  Makes it easier to do the books if I have the names handy.

PayPal payment made this morning.  Squawk if you don't see it.
