### ISSUE TITLE
Grant to bgbsww for Toponaming migration

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FPA#130]
As approved by the FPA members, a grant of USD 4800 to bgbsww in 4 installments.

**Comment by yorikvanhavre** [comment]
Paid today a first installment of USD 1200 via paypal

**Comment by chennes** [comment]
His second report is here: https://github.com/FreeCAD/FPA/blob/main/reports/Toponaming/bgbsww_report2.md
Payment two should now follow.

**Comment by WandererFan** [comment]
2024-02-19

You'll send 1.161,75 EUR
PayPal fee 1,99 EUR
Total 1.163,74 EUR
Payment delivery
In seconds
Bradley McLean will get 1.200,00 USD
Conversion rate: 1 EUR = 1,0329 USD

**Comment by chennes** [comment]
Report 3 is now live: https://github.com/FreeCAD/FPA/blob/main/reports/Toponaming/bgbsww_report3.md

Payment can be issued now.

**Comment by WandererFan** [comment]
You're sending with PayPal Balance (USD) Preferred 162,03 USD
BNP Paribas Fortis SA/NV Current Account ••••4531  992,39 EUR

You'll send 1.145,00 EUR
PayPal fee 1,99 EUR
Total 1.146,99 EUR
Payment delivery In seconds
Bradley McLean will get 1.200,00 USD
Conversion rate: 1 EUR = 1,0480 USD

**Comment by chennes** [comment]
Report 4 is now live: https://github.com/FreeCAD/FPA/blob/main/reports/Toponaming/bgbsww_report4.md

Final payment can be issued now.
