### ISSUE TITLE
2024 FOSDEM Travel Grant for CalligaroV

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#134]
Vincenzo Calligaro requested FOSDEM Travel Grant via PM to @wandererfan.

**Comment by WandererFan** [comment]
Hotel     289.00 EUR
Air             83.98 EUR
Transfers  17.95 EUR
                   19.95 EUR

Total     410.88 EUR

[CalligaroV-FreeCAD-BRUXELLES.pdf](https://github.com/FreeCAD/FPA/files/14239985/CalligaroV-FreeCAD-BRUXELLES.pdf)

**Comment by WandererFan** [comment]
To be paid via bank transfer.   IBan/SWIFT numbers to follow.

**Comment by yorikvanhavre** [comment]
Paid today 410.88 EUR via BNP transfer
