### ISSUE TITLE
 2024 FOSDEM Travel Grant for Michael Schloh

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#137]
Michael requests a grant via email to fpa@freecad.org

"I request:

125 EUR flight
290 EUR hotel
40 EUR local transportation
455 EUR total"

**Comment by WandererFan** [comment]
"After uploading to you the receipts by Telegram, I calculated the exact
amount according to the receipts. Please transfer 474,51 EUR to my bank
account, thank you!

Name: Michael Schloh"

I have the IBAN for this.

**Comment by yorikvanhavre** [comment]
Paid today 474.51 EUR via BNP transfer
