### ISSUE TITLE
FPADF Grant to @CalligaroV for Toponaming migration

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#150]
From: https://forum.freecad.org/viewtopic.php?t=84484

Total grant of 3400 EUR

Four payments of 850€ will be made, biweekly, following delivery of a progress report including a description of work completed over the previous two-week period

**Comment by yorikvanhavre** [comment]
Paid today payment 01 and 02, total 1700 EUR, via BNP transfer

**Comment by chennes** [comment]
Next report is here: https://github.com/FreeCAD/FPA/pull/161

**Comment by yorikvanhavre** [comment]
Paid today part 03 of 850 EUR via BNP transfer

**Comment by chennes** [comment]
Final report is here: https://github.com/FreeCAD/FPA/blob/main/reports/Toponaming/calligarov_report4.md

**Comment by yorikvanhavre** [comment]
Paid today 850 EUR via BNP transfer. This closes this issue.
