### ISSUE TITLE
Annual Report on blog has dead links

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#166]
Links to annualreports/_images/2024/* are not working, giving 404 or showing as plain text (not hyperlinks).

Link to https://github.com/FreeCAD/FPA/blob/main/reports/2023_09_27_Prokoudine.md goes to github page and is not displayed as markdown.

Link work in local version of report.

**Comment by yorikvanhavre** [comment]
report links are fixed with https://github.com/FreeCAD/FPA/commit/43e9d7f7e2143432c76449fa523527a4459d858d

to have Alex's report rendered, I think it must be linked from somewhere else... Not sure where?
