### ISSUE TITLE
Travel expenses reimbursment to Amulya - FOSSASIA

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FPA#187]
By decision of the FPA members, the FPA is reimbursing the travel costs of the 3 community members who went to FOSSASIA in 2024. Ajinkya submitted his own expenses in #182 , this issue covers the costs of both Amulya and Harshita, according to the receipts they sent to the FPA via email. Total is 666 USD

**Comment by WandererFan** [comment]
Related issue:  Cash Advance re Travel to FOSSASIA - Paritosh #165
Cash advance was 1020 USD.    Is this amount the excess of actual over advance?

**Comment by WandererFan** [comment]
Travellers: Amulya, Harshita, Ajinkya

Budget: 2050 USD 

Cash advance to Amulya: 1020
Travel claim for Amulya & Harshita: 666 USD (this issue)
Travel claim for Ajinkya: 360 USD   

Total 2046 USD
