### ISSUE TITLE
Purchase of technical norms for dimensioning & technical drawing

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FPA#189]
Purchase of two technical norms related to https://github.com/FreeCAD/FreeCAD/pull/13659

* ASME Y14_3_2012_R2018 - Orthographic and pictorial views, for USD87.12
* ISO 128-3_2022 - Technical product documentation part 3, for CHF173

**Comment by yorikvanhavre** [comment]
Paid today USD87.12 + CHF173 via credit card

**Comment by WandererFan** [comment]
ECB exchange 2024-05-15
1 EUR = 0.98 CHF
1 EUR = 1.0832 USD

**Comment by yorikvanhavre** [comment]
Actual amount charged in EUR:
- ISO: 178.96 EUR
- ASME: 81.46 EUR
