### ISSUE TITLE
Hosting costs bounty

### ISSUE THREAD

**Issue by kkremitzki** [FreeCAD/FPA#2]
Creating an issue to track request of payout for hosting costs from November 2020 to April 2022, inclusive. Total cost $802.31.

**Comment by kkremitzki** [comment]
Certainly, just transferred it.

**Comment by adrianinsaval** [comment]
out of curiosity, what are the specs for the next tier that was requested? And how much of it is freecad currently using?

**Comment by berndhahnebach** [comment]
Does it mean ATM we do pay for the advertising we do make for them ... We are really friendly people, are we :-)

**Comment by adrianinsaval** [comment]
what was the outcome of this? are the servers still costing money?

**Comment by kkremitzki** [comment]
No, it was resolved on June 16th.
