### ISSUE TITLE
FPADF Grant to @bgbsww for Toponaming work (second grant)

### ISSUE THREAD

**Issue by chennes** [FreeCAD/FPA#200]
Brad has delivered his final report: rather than breaking the payment up into stages, he's doing it all at once, post-grant-completion, so we should pay him the total grant amount ($5000 USD).

https://github.com/FreeCAD/FPA/blob/main/reports/Toponaming/bgbsww_grant2_report.md

**Comment by WandererFan** [comment]
Approval post:  https://forum.freecad.org/viewtopic.php?t=86286

**Comment by WandererFan** [comment]
Paid today (2024-06-04) via PayPal

You're sending with
PayPal Balance (USD)    270,41 USD
PayPal Balance (EUR)  2.000,00 EUR
BNP Paribas Fortis SA/NV 2.553,24 EUR

You'll send  4.811,46 EUR
PayPal fee       1,99 EUR
Total        4.813,45 EUR

Bradley McLean will get 5.000,00 USD
Conversion rate: 1 EUR = 1,0392 USD

**Comment by Eldo420** [comment]
Pay what? Need paypal?... :)
