### ISSUE TITLE
560 USD for travel to IndiaFOSS

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#229]
per FPA vote:  [560 USD for travel to IndiaFOSS](https://forum.freecad.org/viewtopic.php?t=89690)

**Comment by WandererFan** [comment]
@yorikvanhavre payment requested by bank transfer in email to fpa.

**Comment by yorikvanhavre** [comment]
Paid today 528,34 EUR (≃ 560 USD + 15 EUR transfer fee) to @AmulyaParisosh via BNP transfer
