### ISSUE TITLE
Honorary grant to flachyjoe

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FPA#234]
Grant of USD 1000 to flachyjoe in recognition for his hard work on the 1.0 release, awarded by the FPA on https://forum.freecad.org/viewtopic.php?t=90834

**Comment by yorikvanhavre** [comment]
Paid today to @flachyjoe 908 EUR ≃ 1000 USD via BNP transfer

**Comment by FlachyJoe** [comment]
I confirmed I got the fund yesterday on my bank account. Thank you!
