### ISSUE TITLE
[Bug] FPA Development Fund application process is not public

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#24]
The FPA has created a Development Fund (https://forum.freecadweb.org/viewtopic.php?f=43&t=71849) and awarded a first grant (https://forum.freecadweb.org/viewtopic.php?f=43&t=71842), but the grant application process has not been made public.

The lack of a public process reflects poorly on the FPA "as a community-owned project that functions transparently".  

The lack of a public process also limits the pool of potential applicants.

**Comment by WandererFan** [comment]
Closed as completed.

**Comment by adrianinsaval** [comment]
perhaps make a template for the application and publish this on the forum too? It's pretty obscure right now.
