### ISSUE TITLE
Blocker Issue Bounties

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#254]
FPA approved $500 bounties (up to $6000 total) for fixing issues marked as blockers for v1.0 - https://forum.freecad.org/viewtopic.php?t=91485

**Comment by WandererFan** [comment]
Paid today $500 + $2.04 PayPal fee  to mwganson@gmail.com for issue #17235, pr 17436.

**Comment by yorikvanhavre** [comment]
Paid today 474 EUR ( ≃ 500 USD) via BNP transfer to @hyarion for issue [#17280](https://github.com/FreeCAD/FreeCAD/issues/17280), PR [#17367](https://github.com/FreeCAD/FreeCAD/pull/17367).

**Comment by yorikvanhavre** [comment]
Paid today 968,90 EUR (≃ 1000 USD) via BNP transfer to Ondsel ( ping @sliptonic ) for issues  https://github.com/FreeCAD/FreeCAD/issues/15655 and https://github.com/FreeCAD/FreeCAD/issues/16702

**Comment by yorikvanhavre** [comment]
Paid today 476.00 EUR (≃ 500 USD) via BNP transfer to @kadet1090 for issue https://github.com/FreeCAD/FreeCAD/issues/16072 - PR https://github.com/FreeCAD/FreeCAD/pull/17435

**Comment by yorikvanhavre** [comment]
All the bounties have now been paid, total paid by the FPA is 6x500+2.04 = 3002.04 USD
