### ISSUE TITLE
Postaddress of the FPA

### ISSUE THREAD

**Issue by berndhahnebach** [FreeCAD/FPA#27]
ATM I am trying to apply for membership in this organisation: https://bauen-digital.ch/de/

see disscusion here: https://forum.freecadweb.org/viewtopic.php?f=41&t=66771#p609285

For this I might need a Postaddress

cheers Bernd

**Comment by yorikvanhavre** [comment]
Replying on the forum to not expose the address unnecessarily :sweat_smile:
