### ISSUE TITLE
Create a sponsoring page

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FPA#3]
Create a sponsoring page to be inserted on the website. This page should show:

* What the FPA is
* What are the sponsoring options, tiers, etc.
* How can one donate to the project
* Current sponsors
* Who to contact

Also, we need a clear, unified "tiers" system for sponsoring pages like github sponsors or opencollective with:

* one-time and recurrent donations
* what's for you if you participate

**Comment by yorikvanhavre** [comment]
Maybe... But I'm not a fan of suggesting donations INSIDE FreeCAD itself (I've replied on the forum too)

**Comment by yorikvanhavre** [comment]
Done with https://github.com/FreeCAD/FreeCAD-Homepage/pull/92

**Comment by MisterMakerNL** [comment]
Is it an idea to do a community contest on making "badges".
I was thinking about making machine plates but in a badge form. But it's probably better to let everyone have a go.

**Comment by yorikvanhavre** [comment]
In any case, the idea is interesting: Provide graphical material for sponsors to put on their website. I'll add that to #8
