### ISSUE TITLE
FOSDEM Travel Grant to Chris Hennes

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#55]
US$500  to @chennes re FOSDEM Travel Grant program.

- add 10% BountySource Fee.

**Comment by WandererFan** [comment]
Bounty posted on BountySource https://app.bountysource.com/issues/116947845-fosdem-travel-grant-to-chris-hennes

**Comment by chennes** [comment]
I have told BountySource that I am working on this.

**Comment by WandererFan** [comment]
closing as resolved.
