### ISSUE TITLE
Blog Content Paul J. Tadrous

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#56]
Blog content payment to Paul J. Tadrous - US$100

**Comment by luzpaz** [comment]
Did this get done ?

**Comment by WandererFan** [comment]
IIRC, I asked Paul how he wanted the money paid (PayPal or bank transfer), but there was no response.

**Comment by luzpaz** [comment]
Ping @TadPath

**Comment by TadPath** [comment]
I asked if it could go to my PayPal donation link (optarc) and I thought that was going to happen - but trail went cold and I didn't pursue it. Link is here (and on my GitHub page): https://www.paypal.com/donate/?hosted_button_id=NPMYJKJATDLQ4
if that is still an option?

**Comment by WandererFan** [comment]
Paid by PayPal 100USD >> 77.42GBP
Thanks for donating 77,42 £ GBP to OptArc
Transaction ID: 32F01879329644255

**Comment by TadPath** [comment]
Yep - I confirm. Donation received with Thanks!
