### ISSUE TITLE
Create a FPA page

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FPA#7]
Create a page for the FreeCAD homepage explaining what the FPA is

**Comment by adrianinsaval** [comment]
more or less related, are there plans to finally migrate to freecad.org as the main site?

**Comment by yorikvanhavre** [comment]
Maybe we could do it after 0.20? I think it's mainly the forum that's annoying now...

**Comment by yorikvanhavre** [comment]
Closing this issue as we'd better keep using this github account for now.
The freecadweb.org -> freecad.org migration is tracked at https://github.com/FreeCAD/FreeCAD-Homepage/issues/94
