### ISSUE TITLE
Get a CA certificate for the FPA

### ISSUE THREAD

**Issue by yorikvanhavre** [FreeCAD/FPA#73]
A CA certificate is a certificate issued by an authority (as opposed to a self-signed certificate), that certifies your identity. CA certificates are commonly used on websites, but can also be used to sign applications. CA certifcates can usually be purchased in different flavours (individual or corporate, with or without subdomains). It costs between USD 200 and 350 a year.

**Note** Linux Appimages are typically signed with gpg keys, and Apple installers with Apple developer IDs. So a CA certificate would basically only be of use to sign Windows packages. So purchasing a CA certificate would have two uses for the FPA:

* Certify the freecad.org website (and all of its subdomains)
* Sign the windows installer packages

A corporate, subdomain-enabled CA certificate would cost around USD 250 / year, would display "The FreeCAD project association" as the owner when someone requests security details at freecad.org, and would make the FreeCAD Windows installer signed by the FPA.

Microsoft [recommends purchasing a certificate from their "partners"](https://support.microsoft.com/en-us/office/find-digital-id-or-digital-signature-services-b06cfc76-56a1-4a74-b2dd-91a55de79cdf) but they are more pricey at about USD 350 for a corporate certificate. Gandi.net, where the freecad.org domain is registered, also [sells CA corp certifcates](https://www.gandi.net/en/security?c=BE&taxes=no#pro) for around USD 250. [Description of Pro certificates](https://docs.gandi.net/en/ssl/description/professional.html)

Certificates come as SSL certificates which can be directly used with websites, but can also [easily be converted to the pfx format](https://docs.gandi.net/en/ssl/faq/index.html#how-do-i-export-my-ssl-certificate-and-private-key-as-a-pfx-file) ([other tutorial](https://hungdoan.com/2021/04/04/how-to-buy-and-convert-ssl-certificate-to-pfx-format/)) which is used by the signtool.exe tool to sign Windows executables.

The certificate comes as a SSL certificate and can be immediately used on websites, and can

**Comment by adrianinsaval** [comment]
Are they really the same? from what I understand a code signing certificate (for windows) is different from an SSL certificate.

And there seems to be different tiers for code signing certificates: https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro/66582477#66582477

here certificates are offered with discount for opensource projects: https://shop.certum.eu/data-safety/code-signing-certificates.html?as_code_signing_rodzaj=5651

bot it's not clear to me if it's OV or EV

**Comment by yorikvanhavre** [comment]
What I read everywhere is that you can convert any ssl certificate to pfx if you have a crt file that the authority provides too. So the thing is to verify that point prior to buying.

But there is one thing I was not aware, Microsoft has a list of [trusted authorities](https://ccadb.my.salesforce-sites.com/microsoft/IncludedCACertificateReportForMSFT). Buying a certificate outside of those approved apparently is not much better than a self-signed one. Gandi is not in that list, so that option is not good for us.

The certum cert is interesting, it's cheap, and certum is in the approved list. But indeed I can't find if it includes verification of the FPA (that would be EV) or not. It also seems to come with a complex bundle of card reader and proprietary system... Might not be very practical, because it will allow only one person (who has the card) to sign

I think we need to look further...

**Comment by adrianinsaval** [comment]
I think MS now requires that you use that kind of card for the code signing certificate.

they also have regular EV certificates: https://shop.certum.eu/data-safety/code-signing-certificates.html?as_code_signing_rodzaj=5653

but those aren't cheap so I don't know if that's convenient

**Comment by yorikvanhavre** [comment]
Indeed this is more expensive than we thought... But it would still be doable if it is worth it, I guess that's what we need to look at I guess... I see as inconvenients:

* It's expensive
* Only one person has the physical card and can sign the package

And on the plus side:

* It allows people to install FreeCAD on Windows without any warning <-- That's what we need to make sure of. From the [stackoverflow](https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro/66582477#66582477) you cited above, it's not guaranteed and takes some time

**Comment by adrianinsaval** [comment]
EV certificates are instantaneous as I understood it, that's why they are so much more expensive. But I'm not sure if it's worth it, since eventually the warning also goes away for an unsigned executable.
The non EV certificate is only worth buying if we are going to make several point releases within the year, after an initial release with that certificate all point releases with the same certificate should be trusted.

**Comment by yorikvanhavre** [comment]
Considering godaddy: https://www.godaddy.com/web-security/ev-ssl-certificate
* USD 200/year
* 5/7 days to obtain
* No physical device (needs a [private key](https://www.godaddy.com/help/wheres-my-private-key-32300))
* Can be [converted to pfx](https://community.godaddy.com/s/question/0D53t00006Vm6vXCAR/how-do-i-convert-crt-to-pfx-or-get-a-pfx-certificate)

**Comment by yorikvanhavre** [comment]
Bought today - paid via Paypal.
Waiting on purchase confirmation and start of the validation process

**Comment by yorikvanhavre** [comment]
update - we had to provide a letter written by a lawyer ( #90 ) attesting that the FPA exists. This is now done and being analyzed by godaddy...

**Comment by maxwxyz** [comment]
is this still relevant?

**Comment by yorikvanhavre** [comment]
This is now done - see https://github.com/FreeCAD/FPA/issues/5#issuecomment-2199943946 We purchased a new certificate that is now used for 1.0
