### ISSUE TITLE
Missing 2023 budget

### ISSUE THREAD

**Issue by benj5378** [FreeCAD/FPA#77]
2023 budget link leads to 2022 budget page :(

**Comment by benj5378** [comment]
2022 report financial statements links are all broken too (3 pcs)

**Comment by yorikvanhavre** [comment]
We actually never published a separate 2023 budget, we did a "all-in-one" document with the 2022. Indeed it was wrongly linked.

**Comment by benj5378** [comment]
@yorikvanhavre Was thinking of updating the layout to make it look a lot more modern with FreeCAD logo and such. Are you open to this? I don't know if the current pipelines can do anything else than standard GitHub page layouts.

**Comment by yorikvanhavre** [comment]
Of course! The current layout I think is just a theme that @sliptonic selected. We could totally make things nicer!
Also, the pages engine has some weird things where links sometimes don't work correctly inside github code view (not in pages). That should also be changed at some point, I think the whole site should look good both rendered in pages and on github
