### ISSUE TITLE
Vancouver travel grant for @chennes

### ISSUE THREAD

**Issue by chennes** [FreeCAD/FPA#84]
I'm asking for travel expense reimbursment of $500 USD to defray expenses incurred in travel to the Vancouver Hackathon. Hotel receipt attached.
[Norman2FPublicCopier@pioneerlibrarysystem.org_20230830_125425[37].pdf](https://github.com/FreeCAD/FPA/files/12478837/Norman2FPublicCopier%40pioneerlibrarysystem.org_20230830_125425.37.pdf)

**Comment by WandererFan** [comment]
Paid via PayPal.
