### ISSUE TITLE
FPADF Grant to @AgCaliva Final Installment USD 300

### ISSUE THREAD

**Issue by WandererFan** [FreeCAD/FPA#96]
Final payment of USD 300 to @AgCaliva via PayPal to @marchucaliva.

Approval: https://forum.freecad.org/viewtopic.php?t=80112

Merged PR: Adding "ProjectUnitSystem" support to project files. #9521 https://github.com/FreeCAD/FreeCAD/pull/9521

**Comment by sliptonic** [comment]
Approved.  The project became more complex than expected.  The final PR did not include the per-constraint feature.  That can be considered for a future unit of work.
